language: node_js
node_js:
- 10

deploy:
  edge: true
  provider: npm
  email: cemyderin@gmail.com
  api_key:
    secure: lCQ4S5t2p/QNPLaElBR89g0LEfkUKDJLBW1sJGLZ/SsMZTAfNjY6gP6WUS5tsLGZ0jS+4L1dEKBFhYE7KKg5Qtfq77DGpoJgCCJ2wWUNeRpbuMqkU3bXui9Dlu7GezAfbYdErE108/tvRejhpXM4Qs+rdK8hYOvn02M9hEsZ3FqM49XxKXTl/EZsVHrHSWr02BV1Stis5YbgZfbSFfVZll9bVoRYHhc+wOteTkH3fwt0YONjz0nKWH5rMa4rMRrbJb9WFzuUbsB1LEaFQ7hNAuN8QKfNkkaxv3VXY6fM+ZX/Hb1dji5MWeZU1zxUmXJGxt1PVYAxRt8vD0fMH2xMND0+X6SamzISb1x6JzR014qjHaKW14L4l64uVu4bZcHPjEdhN8QVTA7HqZuWiGahdvlvi45IVq6O7KpY15mbxRBv9SU28vvjygkuvR6RcZI6Kvc/T+5W1M1Y5pVgRXvfnzRwDTZeh471iUDWLWDdJK5LDSegsmjQv0qrob4dRtA52UsLB771SJDX9pfyVLIsdl00mYT9MWMybSWEUwT8IvdeU23hfHIbl5vTjl7IXyVbVEqeVfv3yanGJpfHpmy0BCZf3AAcuaZnoN5G9hInx36hVEqotaRLJWoiBbuooCnidifLVslnjwoytTfYZ9lY+LtjyPwrYjKe0vfNEZ+qWoE=
  on:
    repo: cemderin/react-base-element
    branch: master
